version: '2'

services:
  apache:
    container_name: apache
    build: ./apache
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
    volumes:
      - ../www:/var/www
      - ./log:/var/log
      - ./.ssh:/root/.ssh
  php:
    build: ./php/php7-fpm-alpine
    hostname: 'dev'    
    container_name: php7
    volumes:
      - ../www:/var/www      
  php5:
    container_name: php5
    build: ./php/php5.4-fpm      
    hostname: 'dev5'    
    volumes:
      - ../www:/var/www
  db:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user-pass'
      MYSQL_ROOT_PASSWORD: 'root-pass'
    ports:
      - '3336:3306'
    expose: 
      - '3306'    
